"""SHAP summary plot and model card, generated from training metadata so numbers can't go stale."""

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import shap  # noqa: E402

from fraud.features import FEATURES  # noqa: E402


def shap_summary_plot(booster, X: np.ndarray, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    explainer = shap.TreeExplainer(booster)
    values = explainer.shap_values(X)
    plt.figure()
    shap.summary_plot(values, X, feature_names=list(FEATURES), show=False, max_display=15)
    plt.title("What drives the fraud score (SHAP, test period)")
    plt.tight_layout()
    plt.savefig(path, dpi=120)
    plt.close()


def _pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def render_model_card(meta: dict, path: Path, image: Path) -> None:
    m = meta["metrics"]
    f, h, r = m["flagged_review_or_high"], m["auto_declined_high"], m["rules_fallback"]
    patterns = "\n".join(
        f"| {name.replace('_', ' ')} | {v['count']} | {_pct(v['model_recall'])} | {_pct(v['rules_recall'])} |"
        for name, v in m["recall_by_pattern"].items())
    rel_image = Path("images") / image.name
    weakest_name, weakest = min(m["recall_by_pattern"].items(), key=lambda kv: kv[1]["model_recall"])
    path.write_text(f"""# Model card: CardFlow fraud model

> Generated by `services/fraud-service/training/train.py`; do not edit by hand. Regenerate with `make train`.

| | |
|---|---|
| Model version | `{meta["model_version"]}` |
| Trained | {meta["trained_at"]} |
| Algorithm | XGBoost gradient-boosted trees, {meta["trees"]} trees, max depth {meta["params"]["max_depth"]} |
| Output | Probability-like score in [0, 1], a band (LOW / REVIEW / HIGH) and the top 3 reason codes |
| Intended use | Real-time scoring of synthetic card authorizations in the CardFlow demo |
| Not for | Real cardholders or real payment decisions |

## Data
- **Fully synthetic**, from the CardFlow simulator (`python -m cardflow_sim dataset`, seed 7): {meta["dataset"]["rows"]:,} transactions, {_pct(meta["dataset"]["fraud_rate"])} fraud.
- No personal data, no demographic attributes, and no proxies for them (location is only used relative to the card's own history).
- Fraud patterns injected: velocity bursts, first-time high-risk categories, impossible travel, amount spikes. Legitimate traffic includes trips, big purchases, new categories and short bursts, so the patterns overlap with normal behaviour.

## Split (by time, never random)
| Train | Validation (early stopping + thresholds) | Test (reported below) |
|---|---|---|
| days {meta["split"]["train_days"]} ({meta["split"]["train_rows"]:,} rows) | days {meta["split"]["validation_days"]} ({meta["split"]["validation_rows"]:,} rows) | days {meta["split"]["test_days"]} ({m["test_rows"]:,} rows, {m["test_fraud"]} fraud) |

A random split would leak the future into training (the same burst would appear in both sets) and inflate every metric.

## Features ({len(meta["features"])})
Computed by `fraud/features.py` from the card's own previous transactions (last 30 days, at most 100), identically in training and serving: amount and amount vs. the card's average, transaction counts in 10 min / 1 h / 24 h, spend in the last hour, time since the last transaction, distance and implied speed from the last in-person transaction, distance from the card's usual location, first time in this category, high-risk category, online vs. in person, hour of day, distinct merchants in the last hour.

## Results on the test period
Accuracy is not reported: with {_pct(m["test_fraud"] / m["test_rows"])} fraud, always answering "legit" would score {_pct(1 - m["test_fraud"] / m["test_rows"])}.

| Metric | Value |
|---|---|
| **PR-AUC** (average precision) | **{m["pr_auc"]}** (random would be {m["baseline_pr_auc_if_random"]}) |
| ROC-AUC | {m["roc_auc"]} |

| Policy | Precision | Recall | Share of all charges |
|---|---|---|---|
| **Flag for review or decline** (score ≥ {meta["thresholds"]["review"]:.4f}) | {_pct(f["precision"])} | **{_pct(f["recall"])}** | {_pct(f["flag_rate"])} |
| **Auto-decline** (score ≥ {meta["thresholds"]["high"]:.4f}) | **{_pct(h["precision"])}** | {_pct(h["recall"])} | {_pct(h["flag_rate"])} |
| Rule-based fallback (flag for review) | {_pct(r["precision"])} | {_pct(r["recall"])} | {_pct(r["flag_rate"])} |

**Recall by fraud pattern** (flagged for review or declined):

| Pattern | Test cases | Model | Rules fallback |
|---|---|---|---|
{patterns}

**Scoring latency** (features + prediction + SHAP, one transaction, in-process): p50 {m["scoring_latency_ms"]["p50"]} ms, p95 {m["scoring_latency_ms"]["p95"]} ms.

## Thresholds
- **REVIEW** = {meta["threshold_policy"]["review"]}. Charges between REVIEW and HIGH go to a human analyst; the model never makes the final call on borderline cases.
- **HIGH** = {meta["threshold_policy"]["high"]}. Only these are declined automatically.
- Chosen on validation data only, then measured once on test.

## Explainability
Each score comes with up to 3 reason codes from per-transaction SHAP values (XGBoost's built-in TreeSHAP, `pred_contribs=True`). Only features that pushed the score *up* become reasons.

![SHAP summary]({rel_image})

## Limitations
- Synthetic data: the patterns are cleaner than real fraud, so real-world performance would be lower. The value here is the pipeline, not the numbers.
- Weakest pattern: **{weakest_name.replace('_', ' ')}** ({_pct(weakest["model_recall"])} recall). A large purchase from a card with little history looks like a legitimate big purchase; more history per card, or merchant-level signals, would help.
- Cold start: a card with no history gets no velocity or location-change signal for its first charges.
- Fraudsters adapt; a real model needs monitoring for drift and regular retraining with labels from chargebacks and analyst decisions.
- Thresholds trade analyst workload against missed fraud; the review share above is the workload.

## Fallback
If fraud-service is slow or down, authorization-service uses simple rules (the "Rule-based fallback" row): it never auto-declines and only routes large or high-risk-category charges to review.
""")
